### PR TITLE
[crash] Add --recv-selector receiver option

### LINKED ISSUE #14: Implement --recv-selector receiver option
Essentially all tests in JAMQMsgSelectorfffTests are affected

    stderr: "/home/jdanek/Work/repos/cli-proton-ruby/lib/options/sr_common_option_parser.rb:55:in `parse\': invalid option: --recv-selector (OptionParser::InvalidOption)"

```
cli: "aacf"
type: "receiver"
options: "--log-msgs"
options: "dict"
options: "--count"
options: "0"
options: "--recv-selector"
options: "%a = \'aeshah1M\'"
options: "--timeout"
options: "2"
options: "--broker"
options: "amqp://127.0.0.1:5672/unknowntestSdFU4pF"
wrapperOptions {
}
```

### PR DESCRIPTION
**Pull request by jirkadanek**
This closes #14

### CODE REVIEW

**Comment by jirkadanek** [comment]
Currently crashes with the latest master

```
% ruby bin/cli-proton-ruby-receiver --recv-selector a=b
/home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/wrapper.rb:130: [BUG] Segmentation fault at 0x0000000000000060
ruby 2.5.0p0 (2017-12-25) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0023 e:000022 CFUNC  :pn_inspect
c:0005 p:0052 s:0017 e:000016 METHOD /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/wrapper.rb:130 [FINISH]
c:0004 p:---- s:0012 e:000011 CFUNC  :to_str
c:0003 p:---- s:0009 e:000008 CFUNC  :to_s
c:0002 p:---- s:0006 e:000005 CFUNC  :message
c:0001 p:0000 s:0003 E:0017a0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
bin/cli-proton-ruby-receiver:0:in `message'
bin/cli-proton-ruby-receiver:0:in `to_s'
bin/cli-proton-ruby-receiver:0:in `to_str'
/home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/wrapper.rb:130:in `inspect'
/home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/wrapper.rb:130:in `pn_inspect'

-- Machine register context ------------------------------------------------
 RIP: 0x00007efe562caca8 RBP: 0x00000000028b44f0 RSP: 0x00007ffe3536c4a0
 RAX: 0x0000000002834f00 RBX: 0x0000000002914448 RCX: 0x0000000000000000
 RDX: 0x00000000028b44f0 RDI: 0x00000000028b44f0 RSI: 0x0000000002914448
  R8: 0x00007efe5e9c1608  R9: 0x00007efe5655781d R10: 0x0d30f6462039f989
 R11: 0x0000000002641a70 R12: 0x0000000000000000 R13: 0x0000000000000002
 R14: 0x00000000027ab758 R15: 0x00000000026385b0 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_print_backtrace+0x15) [0x7efe5e993d95]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1cbfcc) [0x7efe5e993fcc]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x918f7) [0x7efe5e8598f7]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x15a5f2) [0x7efe5e9225f2]
/nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread.so.0(0x7efe5e5bbdd0) [0x7efe5e5bbdd0]
/home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11(pn_class_inspect+0x28) [0x7efe562caca8] ../proton-c/src/core/object/object.c:182
/home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so(_wrap_pn_inspect+0x73) [0x7efe56522b83]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1af747) [0x7efe5e977747]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4073) [0x7efe5e98c073]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1ba897) [0x7efe5e982897]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1beb87) [0x7efe5e986b87]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c487c) [0x7efe5e98c87c]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c59af) [0x7efe5e98d9af]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_funcallv+0x2e) [0x7efe5e98e10e]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_inspect+0x14) [0x7efe5e8b9324]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_protect+0x139) [0x7efe5e85fb29]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x92e20) [0x7efe5e85ae20]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4928) [0x7efe5e98c928]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4ee0) [0x7efe5e98cee0]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0xf1eff) [0x7efe5e8b9eff]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_String+0x9) [0x7efe5e8bac39]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4928) [0x7efe5e98c928]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c59af) [0x7efe5e98d9af]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(rb_funcallv+0x2e) [0x7efe5e98e10e]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4928) [0x7efe5e98c928]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x1c4ee0) [0x7efe5e98cee0]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x98609) [0x7efe5e860609]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x9885c) [0x7efe5e86085c]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(0x989db) [0x7efe5e8609db]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(ruby_cleanup+0x1e4) [0x7efe5e861144]
/nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5(ruby_run_node+0x35) [0x7efe5e8613d5]
ruby(0x4009ab) [0x4009ab]
/nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libc.so.6(__libc_start_main+0xf0) [0x7efe5da91020]
ruby(_start+0x2a) [0x4009fa]

-- Other runtime information -----------------------------------------------

* Loaded script: bin/cli-proton-ruby-receiver

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
    5 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
    6 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/rbconfig.rb
    7 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/compatibility.rb
    8 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/defaults.rb
    9 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/deprecate.rb
   10 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/errors.rb
   11 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/version.rb
   12 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/requirement.rb
   13 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/platform.rb
   14 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/basic_specification.rb
   15 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/stub_specification.rb
   16 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/util/list.rb
   17 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/stringio.so
   18 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb
   19 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/exceptions.rb
   20 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb
   21 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_gem.rb
   22 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/monitor.rb
   23 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb
   24 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb
   25 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/path_support.rb
   26 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
   27 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/date_core.so
   28 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/date.rb
   29 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/delegate.rb
   30 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/weakref.rb
   31 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/securerandom.rb
   32 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/exceptions.rb
   33 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/deprecation.rb
   34 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/version.rb
   35 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/error_handler.rb
   36 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/wrapper.rb
   37 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/util/timeout.rb
   38 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/types/type.rb
   39 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/types/strings.rb
   40 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/types/hash.rb
   41 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/types/array.rb
   42 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/types/described.rb
   43 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/codec/mapping.rb
   44 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/codec/data.rb
   45 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/condition.rb
   46 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/event.rb
   47 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/rfc2396_parser.rb
   48 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/rfc3986_parser.rb
   49 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/common.rb
   50 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/generic.rb
   51 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/ftp.rb
   52 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/http.rb
   53 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/https.rb
   54 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/ldap.rb
   55 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/ldaps.rb
   56 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri/mailto.rb
   57 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/uri.rb
   58 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/uri.rb
   59 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/message.rb
   60 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/endpoint.rb
   61 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/session.rb
   62 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/terminus.rb
   63 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/disposition.rb
   64 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/transfer.rb
   65 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/delivery.rb
   66 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/tracker.rb
   67 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/link.rb
   68 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/sender.rb
   69 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/receiver.rb
   70 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/connection.rb
   71 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/sasl.rb
   72 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/ssl_domain.rb
   73 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/ssl_details.rb
   74 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/ssl.rb
   75 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/transport.rb
   76 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/url.rb
   77 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/socket.so
   78 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/io/wait.so
   79 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/socket.rb
   80 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/connection_driver.rb
   81 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/handler/adapter.rb
   82 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/handler/messaging_adapter.rb
   83 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/messaging_handler.rb
   84 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/set.rb
   85 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/listener.rb
   86 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/core/container.rb
   87 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/handler/reactor_messaging_adapter.rb
   88 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/handler/messaging_handler.rb
   89 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/reactor/container.rb
   90 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/messenger/subscription.rb
   91 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/messenger/tracker_status.rb
   92 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/messenger/tracker.rb
   93 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/messenger/messenger.rb
   94 /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/qpid_proton.rb
   95 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/optparse.rb
   96 /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/ostruct.rb
   97 /home/jdanek/Work/repos/cli-proton-ruby/lib/defaults.rb
   98 /home/jdanek/Work/repos/cli-proton-ruby/lib/options/basic_option_parser.rb
   99 /home/jdanek/Work/repos/cli-proton-ruby/lib/options/sr_common_option_parser.rb
  100 /home/jdanek/Work/repos/cli-proton-ruby/lib/options/receiver_option_parser.rb
  101 /home/jdanek/Work/repos/cli-proton-ruby/lib/formatters/basic_formatter.rb
  102 /home/jdanek/Work/repos/cli-proton-ruby/lib/formatters/dict_formatter.rb
  103 /home/jdanek/Work/repos/cli-proton-ruby/lib/handlers/basic_handler.rb
  104 /home/jdanek/Work/repos/cli-proton-ruby/lib/handlers/sr_common_handler.rb
  105 /home/jdanek/Work/repos/cli-proton-ruby/lib/handlers/receiver_handler.rb
  106 /home/jdanek/Work/repos/cli-proton-ruby/lib/receiver_client.rb

* Process memory map:

00400000-00401000 r-xp 00000000 fe:01 1916241                            /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/bin/ruby
00600000-00601000 r--p 00000000 fe:01 1916241                            /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/bin/ruby
00601000-00602000 rw-p 00001000 fe:01 1916241                            /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/bin/ruby
0244a000-02b55000 rw-p 00000000 00:00 0                                  [heap]
7efe54a2b000-7efe54afd000 r--s 00000000 fe:03 1001692                    /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
7efe54afd000-7efe54c61000 r--s 00000000 fe:03 1709447                    /home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11.3.0
7efe54c61000-7efe54f63000 r--s 00000000 fe:01 1916272                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5.0
7efe54f63000-7efe54f79000 r-xp 00000000 fe:01 2771741                    /nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libgcc_s.so.1
7efe54f79000-7efe55178000 ---p 00016000 fe:01 2771741                    /nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libgcc_s.so.1
7efe55178000-7efe55179000 r--p 00015000 fe:01 2771741                    /nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libgcc_s.so.1
7efe55179000-7efe5517a000 rw-p 00016000 fe:01 2771741                    /nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libgcc_s.so.1
7efe5517a000-7efe5517c000 r-xp 00000000 fe:01 2138875                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7efe5517c000-7efe5537b000 ---p 00002000 fe:01 2138875                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7efe5537b000-7efe5537c000 r--p 00001000 fe:01 2138875                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7efe5537c000-7efe5537d000 rw-p 00002000 fe:01 2138875                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7efe5537d000-7efe553a7000 r-xp 00000000 fe:01 2025641                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/socket.so
7efe553a7000-7efe555a7000 ---p 0002a000 fe:01 2025641                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/socket.so
7efe555a7000-7efe555a8000 r--p 0002a000 fe:01 2025641                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/socket.so
7efe555a8000-7efe555a9000 rw-p 0002b000 fe:01 2025641                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/socket.so
7efe555a9000-7efe555d8000 r-xp 00000000 fe:01 2025578                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/date_core.so
7efe555d8000-7efe557d7000 ---p 0002f000 fe:01 2025578                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/date_core.so
7efe557d7000-7efe557d8000 r--p 0002e000 fe:01 2025578                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/date_core.so
7efe557d8000-7efe557d9000 rw-p 0002f000 fe:01 2025578                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/date_core.so
7efe557d9000-7efe557da000 rw-p 00000000 00:00 0 
7efe557da000-7efe557ed000 r-xp 00000000 fe:01 2762083                    /nix/store/4h0allsz28x9mdirzb4wv51algacxzr7-glibc-2.26-131/lib/libresolv-2.26.so
7efe557ed000-7efe559ec000 ---p 00013000 fe:01 2762083                    /nix/store/4h0allsz28x9mdirzb4wv51algacxzr7-glibc-2.26-131/lib/libresolv-2.26.so
7efe559ec000-7efe559ed000 r--p 00012000 fe:01 2762083                    /nix/store/4h0allsz28x9mdirzb4wv51algacxzr7-glibc-2.26-131/lib/libresolv-2.26.so
7efe559ed000-7efe559ee000 rw-p 00013000 fe:01 2762083                    /nix/store/4h0allsz28x9mdirzb4wv51algacxzr7-glibc-2.26-131/lib/libresolv-2.26.so
7efe559ee000-7efe559f0000 rw-p 00000000 00:00 0 
7efe559f0000-7efe55a0b000 r-xp 00000000 fe:01 2899519                    /nix/store/gq562sk25yklqggn4vdbphd6fvmja9ld-cyrus-sasl-2.1.26/lib/libsasl2.so.3.0.0
7efe55a0b000-7efe55c0b000 ---p 0001b000 fe:01 2899519                    /nix/store/gq562sk25yklqggn4vdbphd6fvmja9ld-cyrus-sasl-2.1.26/lib/libsasl2.so.3.0.0
7efe55c0b000-7efe55c0c000 r--p 0001b000 fe:01 2899519                    /nix/store/gq562sk25yklqggn4vdbphd6fvmja9ld-cyrus-sasl-2.1.26/lib/libsasl2.so.3.0.0
7efe55c0c000-7efe55c0d000 rw-p 0001c000 fe:01 2899519                    /nix/store/gq562sk25yklqggn4vdbphd6fvmja9ld-cyrus-sasl-2.1.26/lib/libsasl2.so.3.0.0
7efe55c0d000-7efe55e1e000 r-xp 00000000 fe:01 2772403                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libcrypto.so.1.0.0
7efe55e1e000-7efe5601d000 ---p 00211000 fe:01 2772403                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libcrypto.so.1.0.0
7efe5601d000-7efe56039000 r--p 00210000 fe:01 2772403                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libcrypto.so.1.0.0
7efe56039000-7efe56044000 rw-p 0022c000 fe:01 2772403                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libcrypto.so.1.0.0
7efe56044000-7efe56048000 rw-p 00000000 00:00 0 
7efe56048000-7efe560ac000 r-xp 00000000 fe:01 2773590                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libssl.so.1.0.0
7efe560ac000-7efe562ab000 ---p 00064000 fe:01 2773590                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libssl.so.1.0.0
7efe562ab000-7efe562b0000 r--p 00063000 fe:01 2773590                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libssl.so.1.0.0
7efe562b0000-7efe562b6000 rw-p 00068000 fe:01 2773590                    /nix/store/1b5l524r05qzgws8k2v7f0p52i0y4nq6-openssl-1.0.2n/lib/libssl.so.1.0.0
7efe562b6000-7efe56308000 r-xp 00000000 fe:03 1709447                    /home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11.3.0
7efe56308000-7efe56507000 ---p 00052000 fe:03 1709447                    /home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11.3.0
7efe56507000-7efe5650a000 r--p 00051000 fe:03 1709447                    /home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11.3.0
7efe5650a000-7efe5650b000 rw-p 00054000 fe:03 1709447                    /home/jdanek/Work/repos/qpid-proton/build/install/lib64/libqpid-proton.so.11.3.0
7efe5650b000-7efe5656a000 r-xp 00000000 fe:03 1001692                    /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
7efe5656a000-7efe5676a000 ---p 0005f000 fe:03 1001692                    /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
7efe5676a000-7efe5676c000 r--p 0005f000 fe:03 1001692                    /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
7efe5676c000-7efe5676f000 rw-p 00061000 fe:03 1001692                    /home/jdanek/.gem/ruby/2.5.0/gems/qpid_proton-0.22.0/lib/cproton.so
7efe5676f000-7efe56770000 rw-p 00000000 00:00 0 
7efe56770000-7efe56777000 r-xp 00000000 fe:01 2025642                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/stringio.so
7efe56777000-7efe56977000 ---p 00007000 fe:01 2025642                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/stringio.so
7efe56977000-7efe56978000 r--p 00007000 fe:01 2025642                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/stringio.so
7efe56978000-7efe56979000 rw-p 00008000 fe:01 2025642                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/stringio.so
7efe56979000-7efe5697c000 r-xp 00000000 fe:01 2138870                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7efe5697c000-7efe56b7b000 ---p 00003000 fe:01 2138870                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7efe56b7b000-7efe56b7c000 r--p 00002000 fe:01 2138870                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7efe56b7c000-7efe56b7d000 rw-p 00003000 fe:01 2138870                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7efe56b7d000-7efe56b7f000 r-xp 00000000 fe:01 2025589                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7efe56b7f000-7efe56d7e000 ---p 00002000 fe:01 2025589                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7efe56d7e000-7efe56d7f000 r--p 00001000 fe:01 2025589                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7efe56d7f000-7efe56d80000 rw-p 00002000 fe:01 2025589                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7efe56d80000-7efe5da70000 r--p 00000000 fe:01 3018874                    /nix/store/j2gcw60796vm639j7zk3fwbyfasbwf27-glibc-locales-2.26-131/lib/locale/locale-archive
7efe5da70000-7efe5dc19000 r-xp 00000000 fe:01 1875892                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libc-2.26.so
7efe5dc19000-7efe5de18000 ---p 001a9000 fe:01 1875892                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libc-2.26.so
7efe5de18000-7efe5de1c000 r--p 001a8000 fe:01 1875892                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libc-2.26.so
7efe5de1c000-7efe5de1e000 rw-p 001ac000 fe:01 1875892                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libc-2.26.so
7efe5de1e000-7efe5de22000 rw-p 00000000 00:00 0 
7efe5de22000-7efe5df6d000 r-xp 00000000 fe:01 1875909                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libm-2.26.so
7efe5df6d000-7efe5e16c000 ---p 0014b000 fe:01 1875909                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libm-2.26.so
7efe5e16c000-7efe5e16d000 r--p 0014a000 fe:01 1875909                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libm-2.26.so
7efe5e16d000-7efe5e16e000 rw-p 0014b000 fe:01 1875909                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libm-2.26.so
7efe5e16e000-7efe5e176000 r-xp 00000000 fe:01 1875901                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libcrypt-2.26.so
7efe5e176000-7efe5e376000 ---p 00008000 fe:01 1875901                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libcrypt-2.26.so
7efe5e376000-7efe5e377000 r--p 00008000 fe:01 1875901                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libcrypt-2.26.so
7efe5e377000-7efe5e378000 rw-p 00009000 fe:01 1875901                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libcrypt-2.26.so
7efe5e378000-7efe5e3a6000 rw-p 00000000 00:00 0 
7efe5e3a6000-7efe5e3a9000 r-xp 00000000 fe:01 1875904                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libdl-2.26.so
7efe5e3a9000-7efe5e5a8000 ---p 00003000 fe:01 1875904                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libdl-2.26.so
7efe5e5a8000-7efe5e5a9000 r--p 00002000 fe:01 1875904                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libdl-2.26.so
7efe5e5a9000-7efe5e5aa000 rw-p 00003000 fe:01 1875904                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libdl-2.26.so
7efe5e5aa000-7efe5e5c3000 r-xp 00000000 fe:01 1875949                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread-2.26.so
7efe5e5c3000-7efe5e7c2000 ---p 00019000 fe:01 1875949                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread-2.26.so
7efe5e7c2000-7efe5e7c3000 r--p 00018000 fe:01 1875949                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread-2.26.so
7efe5e7c3000-7efe5e7c4000 rw-p 00019000 fe:01 1875949                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread-2.26.so
7efe5e7c4000-7efe5e7c8000 rw-p 00000000 00:00 0 
7efe5e7c8000-7efe5ea73000 r-xp 00000000 fe:01 1916272                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5.0
7efe5ea73000-7efe5ec72000 ---p 002ab000 fe:01 1916272                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5.0
7efe5ec72000-7efe5ec7a000 r--p 002aa000 fe:01 1916272                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5.0
7efe5ec7a000-7efe5ec7b000 rw-p 002b2000 fe:01 1916272                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/lib/libruby.so.2.5.0
7efe5ec7b000-7efe5ec8b000 rw-p 00000000 00:00 0 
7efe5ec8b000-7efe5ecb0000 r-xp 00000000 fe:01 1875881                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/ld-2.26.so
7efe5ed1d000-7efe5ed3f000 r--s 00000000 fe:01 1875949                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/libpthread-2.26.so
7efe5ed3f000-7efe5ed42000 r--s 00000000 fe:01 1916241                    /nix/store/0pzx48awg297jv974353m798gpsvcfid-ruby-2.5.0/bin/ruby
7efe5ed42000-7efe5eda3000 rw-p 00000000 00:00 0 
7efe5eda3000-7efe5eda4000 ---p 00000000 00:00 0 
7efe5eda4000-7efe5eeaf000 rw-p 00000000 00:00 0 
7efe5eeaf000-7efe5eeb0000 r--p 00024000 fe:01 1875881                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/ld-2.26.so
7efe5eeb0000-7efe5eeb1000 rw-p 00025000 fe:01 1875881                    /nix/store/1zv5dwifxg5fh08gif8ld3h9f40y8czh-glibc-2.26-115/lib/ld-2.26.so
7efe5eeb1000-7efe5eeb2000 rw-p 00000000 00:00 0 
7ffe34b71000-7ffe35370000 rw-p 00000000 00:00 0                          [stack]
7ffe3537d000-7ffe3537f000 r--p 00000000 00:00 0                          [vvar]
7ffe3537f000-7ffe35381000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    2440 abort      ruby bin/cli-proton-ruby-receiver --recv-selector a=b
```

**Comment by jirkadanek** [comment]
Still blocked, this time on https://issues.apache.org/jira/browse/PROTON-1814

File: lib/handlers/receiver_handler.rb [hunk 1]
```diff
@@ -82,6 +85,10 @@ def initialize(
     # connects receiver client to SRCommonHandler#broker
     # and creates receiver
     def on_container_start(container)
+      # Prepare source options
+      source = {}
+      source[:address] = @broker.amqp_address
+      source[:filter] = @selector if @selector
```
Comment (jirkadanek) [inline lib/handlers/receiver_handler.rb]: @rkubis Question is, do we want to do source = {}, or do it the way you do in PR #31 ?

Comment (rkubis) [reply lib/handlers/receiver_handler.rb]: Hmm, good question.

File: tests/unit/handlers/unit_tests_receiver_handler.rb [hunk 2]
```diff
@@ -101,6 +104,7 @@ def test_receiver_handler_sasl_mechs_argument_initialization
     )
   end # test_receiver_handler_sasl_mechs_argument_initialization
 
+
```
Comment (rkubis) [inline tests/unit/handlers/unit_tests_receiver_handler.rb:123]: Please add some unit tests for receiver handler and receiver option parser.

File: lib/handlers/receiver_handler.rb (hunk 1 above)
Comment (rkubis) [reply lib/handlers/receiver_handler.rb]: This looks better for me now, but some comments can be welcomed.

**Review by rkubis — DISMISSED** [review]
Missing unit tests, otherwise good.

**Comment by jirkadanek** [comment]
PR was updated and now selectors work, no crashes or anything.
